/* auto-generated by NAPI-RS */
/* eslint-disable */
export interface JsApplicationSource {
  module: string
  exports: Array<string>
}

/**
 * One problem, positioned well enough for a bundler to print it.
 *
 * Line and column rather than byte offsets: a loader reports to a human,
 * and every host expects `file:line:column`. Resolving it here means the
 * JS side never has to hold the source to work out where an offset fell.
 */
export interface JsDiagnostic {
  severity: string
  message: string
  line: number
  column: number
}

export interface JsLayoutSource {
  module: string
  exports: Array<string>
  resolved?: string
}

/**
 * What a host can configure.
 *
 * Mode is mandatory. Application hosts additionally provide the exact
 * package/export index they resolved from Layout manifests.
 */
export interface JsOptions {
  mode: string
  libraryOutput?: string
  /**
   * Which major of Solid the output targets: `1` or `2`. Defaults to 1,
   * so a host that has never heard of this option keeps emitting what it
   * always emitted.
   */
  solid?: number
  layoutSources?: Array<JsLayoutSource>
  parseOnly?: boolean
}

export interface JsProjectDiagnostic {
  filename: string
  rule: string
  severity: string
  message: string
  suggestion?: string
  line: number
  column: number
}

export interface JsProjectFile {
  filename: string
  source: string
}

/**
 * Mirrors [`layouts_common::TransformResult`] across the boundary.
 *
 * A separate type rather than a serde derive on the original: napi wants
 * its own representation, and coupling the internal type to the wire
 * format would mean a refactor of one is a breaking change to the other.
 */
export interface JsTransformResult {
  code: string
  diagnostics: Array<JsDiagnostic>
  changed: boolean
  /**
   * True when any diagnostic is an error, so a loader can fail the
   * build without re-inspecting the list.
   */
  failed: boolean
}

export declare function lintApplication(files: Array<JsProjectFile>, sources: Array<JsApplicationSource>): Array<JsProjectDiagnostic>

export declare function lintProject(files: Array<JsProjectFile>): Array<JsProjectDiagnostic>

export declare function transform(source: string, filename: string, options?: JsOptions | undefined | null): JsTransformResult
