import { describe, expect, test } from "bun:test";
import type { RecipeConfig } from "../types";
import { parity } from "./parity.recipe";
import { parityCompiled } from "./parity.compiled";

/**
 * The compiled path and the interpreted path must agree, exactly.
 *
 * `parity.compiled.ts` is generated by the Rust compiler from
 * `parity.recipe.ts` and checked in. Both are imported here and run against
 * the same selections, so a divergence between the two implementations fails
 * in CI rather than in someone's rendered output.
 *
 * Regenerate with:
 *   cargo run -p layouts-transform --example compile -- <path to parity.recipe.ts>
 */

const TONE = [undefined, "neutral", "loud"] as const;
const BOOL = [undefined, true, false] as const;

function selections(): Record<string, unknown>[] {
  const out: Record<string, unknown>[] = [];
  for (const tone of TONE)
    for (const flush of BOOL)
      for (const open of BOOL)
        for (const busy of BOOL) out.push({ tone, flush, open, busy });
  return out;
}

describe("compiled and interpreted resolution agree", () => {
  test("the compiled recipe actually carries a table", () => {
    // Guards against the file being regenerated from a compiler that silently
    // stopped compiling, which would make every case below pass vacuously.
    // `config` is narrowed to the literal that was written, and the compiler
    // adds `_layouts` afterwards, so the property is genuinely absent from
    // the inferred type. Reading it through the declared shape rather than
    // widening `RecipeConfig`, which would let anyone hand-write one.
    const compiled = (parityCompiled.config as RecipeConfig)._layouts;
    const interpreted = (parity.config as RecipeConfig)._layouts;
    expect(compiled).toBeDefined();
    expect(interpreted).toBeUndefined();
  });

  test.each(selections())("selection %j", (selection) => {
    expect(parityCompiled.resolve(selection)).toEqual(parity.resolve(selection));
  });

  test("a consumer override lands identically", () => {
    for (const selection of selections()) {
      expect(parityCompiled.resolve(selection, "mine")).toEqual(
        parity.resolve(selection, "mine"),
      );
    }
  });
});
